# Generated by Django 5.2 on 2025-04-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Desktop', 'Desktop'), ('Game', 'Game'), ('Api', 'Api')], default='Web', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('Production', 'Production'), ('Development', 'Development')], default='Development', max_length=50),
        ),
    ]
